### ISSUE TITLE
API

### ISSUE THREAD

**Issue by tgbhy** [Foulest/Vault#11]
**Before you submit this question, please make sure you have done the following:**

- [X] I have checked the existing documentation for this project
- [x] I have searched the issue tracker for a similar question

**Your Question**
How can we use VaultAPI in plugins for this fork ?

**Comment by tgbhy** [comment]
I have this issue with the API : java.lang.NoClassDefFoundError: net/milkbowl/vault/chat/Chat

**Comment by tgbhy** [comment]
[13:03:32] [Server thread/ERROR]: Error occurred while enabling AntaChat v1.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net/milkbowl/vault/chat/Chat
	at AntaChat-1.0.0.jar/fr.antasia.tgbhy.antachat.AntaChat.setupChat(AntaChat.java:34) ~[AntaChat-1.0.0.jar:?]
	at AntaChat-1.0.0.jar/fr.antasia.tgbhy.antachat.AntaChat.onEnable(AntaChat.java:30) ~[AntaChat-1.0.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-41-fcedb49]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-41-fcedb49]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-41-fcedb49]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-41-fcedb49]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.1.jar:1.21.1-41-fcedb49]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.1.jar:1.21.1-41-fcedb49]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-41-fcedb49]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.1.jar:1.21.1-41-fcedb49]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-41-fcedb49]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.milkbowl.vault.chat.Chat
	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:146) ~[paper-1.21.1.jar:1.21.1-41-fcedb49]
	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:107) ~[paper-1.21.1.jar:1.21.1-41-fcedb49]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 14 more

**Comment by Foulest** [comment]
I need the full log file.

**Comment by Foulest** [comment]
The Vault plugin needs to be in your server's plugins folder.

**Comment by Foulest** [comment]
Did adding the latest version of the plugin to your server's plugins folder solve this problem?

**Comment by luismayme** [comment]
Thanks, I'll give it a look :)
