### ISSUE TITLE
Error occurred while enabling Vault 

### ISSUE THREAD

**Issue by Q2297045667** [Foulest/Vault#16]
He seems to have some issues
folia-1.21.4.jar:1.21.4-DEV-8af1aef

```
[22:59:19] [Server thread/ERROR]: Error occurred while enabling Vault v2.4.5 (Is it up to date?)
java.lang.UnsupportedOperationException: null
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.handle(CraftScheduler.java:517) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:227) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:209) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:173) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
	at Vault-2.4.5.jar/net.milkbowl.vault.Vault.onEnable(Vault.java:69) ~[Vault-2.4.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[folia-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[folia-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:811) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:558) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:326) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:384) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
	at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
```

**Comment by Foulest** [comment]
Fixed in 2.5.0 (hopefully).
